GET http://127.0.0.1:8000/products/

###
GET http://127.0.0.1:8000/products/10

###

PATCH   http://127.0.0.1:8000/products/1/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU5NTY2OTk3LCJpYXQiOjE3NTk1NjY2OTcsImp0aSI6IjliMWUxNzUxODU5MjQyMjg4Nzc5OWYzYjU5ZDIzYmI5IiwidXNlcl9pZCI6IjEifQ.sJtMXph8polBGdTOmZQohxZvWIqvdJyaz532Ls2hhsc

{
  "description": "Sony Scanner"
}
###

DELETE   http://127.0.0.1:8000/products/10/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU5NTY2OTk3LCJpYXQiOjE3NTk1NjY2OTcsImp0aSI6IjliMWUxNzUxODU5MjQyMjg4Nzc5OWYzYjU5ZDIzYmI5IiwidXNlcl9pZCI6IjEifQ.sJtMXph8polBGdTOmZQohxZvWIqvdJyaz532Ls2hhsc

###


POST http://127.0.0.1:8000/products/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU5NzQ4OTYwLCJpYXQiOjE3NTk3NDg2NjAsImp0aSI6IjY5MGIwYzVhZTAzNTQ3ZWViMzljMGRmNjBlNDc0MDYyIiwidXNlcl9pZCI6IjEifQ.-8-AbpzwDEWsf2ridWIEiCtSFgNZl4_e8pPs8v5S0F4

{
    "description": "PlayStation Gaming!",
    "name": "PS5",
    "price": "250",
    "stock": 0
}


###

POST http://127.0.0.1:8000/api/token/ HTTP/1.1
Content-Type: application/json

{
    "username" : "shahriar",
    "password" : "1234"
}



###

GET http://127.0.0.1:8000/orders/ea025189-5067-4b1b-b084-69133745db5f/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYwMDE0NTM1LCJpYXQiOjE3NjAwMTQyMzUsImp0aSI6IjUxYmEwNzg2ZTRkZDRlMDY4MzA0YjY2YWI0ZDAyZWE5IiwidXNlcl9pZCI6IjMifQ.8fx51ZJz3WoP4uakDJ-6wGUPTVP8q-Om-SZYu_al_XA

PUT http://127.0.0.1:8000/orders/ea025189-5067-4b1b-b084-69133745db5f/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYwMDE0MTM3LCJpYXQiOjE3NjAwMTM4MzcsImp0aSI6ImU1ZmU2YmVjYzJiODRjMGNiMzIyYTJiNDU5YzdlMWQzIiwidXNlcl9pZCI6IjMifQ.WSOLIB0E1ACnmTv8_Y_1TCgm2GQBHrkeRdXEKxLQZaY

{
    "status": "Pending",
    "items": [
      {
        "product": 4,
        "quantity": 7
      }
    ]
}

###


DELETE  http://127.0.0.1:8000/orders/ea025189-5067-4b1b-b084-69133745db5f/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYwMDE0NTM1LCJpYXQiOjE3NjAwMTQyMzUsImp0aSI6IjUxYmEwNzg2ZTRkZDRlMDY4MzA0YjY2YWI0ZDAyZWE5IiwidXNlcl9pZCI6IjMifQ.8fx51ZJz3WoP4uakDJ-6wGUPTVP8q-Om-SZYu_al_XA


###

PATCH http://127.0.0.1:8000/orders/c1eb3490-0823-483f-84be-084971b30601/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU5OTE5MDc2LCJpYXQiOjE3NTk5MTg3NzYsImp0aSI6Ijc5YTU3ODhmYjAyZDRiYzZhOTVlODk5MDE0NjJmYjA3IiwidXNlcl9pZCI6IjMifQ.CnuaIg90cJzjtepu4Tqn48JvoH03oYI2iEbagfhWtsw
Content-Type: application/json

{
  "status": "Pending"
}





###

POST http://127.0.0.1:8000/api/token/refresh/ HTTP/1.1
Content-Type: application/json

{
    "refresh" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1OTY1MjAwMywiaWF0IjoxNzU5NTY1NjAzLCJqdGkiOiJmNzkyNzc1NTg3N2E0MmE1YmRjMmZmNTAyYzNkZjQ0OSIsInVzZXJfaWQiOiIzIn0.8Y5dxhMyVCkFYeacaIyyYaTfiMKAnw3RAQ9iUFCpSJM"
}

